// <auto-generated />
using System;
using MarketProj.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketProj.DAL.Migrations
{
    [DbContext(typeof(MarketDB))]
    [Migration("20200615130201_dataSeed_UserProducts")]
    partial class dataSeed_UserProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarketProj.Models.Models.Assets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetsType")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61a1ab98-8a02-475c-a747-4cb09ef1ac8f"),
                            AssetsType = 0,
                            ProductId = new Guid("7d16bcaf-37ac-4e42-8619-38d9afd2e798"),
                            Url = "https://i.ebayimg.com/images/g/RgUAAOSwatBb8s0m/s-l1600.jpg"
                        },
                        new
                        {
                            Id = new Guid("4df146d0-f08e-4e71-a29e-a015ba268ad2"),
                            AssetsType = 0,
                            ProductId = new Guid("7d16bcaf-37ac-4e42-8619-38d9afd2e798"),
                            Url = "https://i.ebayimg.com/images/g/op0AAOSwhnlb8s0f/s-l1600.jpg"
                        },
                        new
                        {
                            Id = new Guid("3ee552e1-0e61-4f3a-b084-4873c96766b3"),
                            AssetsType = 0,
                            ProductId = new Guid("44a49261-e520-48e0-9b8f-32a3287ac366"),
                            Url = "https://www.llbeanbusiness.com/static/cms-img/classic-oxford-shirts-f19.jpg"
                        },
                        new
                        {
                            Id = new Guid("2708b6af-05bd-4618-86b3-e78f07091960"),
                            AssetsType = 0,
                            ProductId = new Guid("44a49261-e520-48e0-9b8f-32a3287ac366"),
                            Url = "https://images-na.ssl-images-amazon.com/images/I/61TWxMB8LFL._AC_UX679_.jpg"
                        },
                        new
                        {
                            Id = new Guid("f5fc548f-603a-4caf-86b9-f82c7aaae219"),
                            AssetsType = 0,
                            ProductId = new Guid("5a0aefdb-46ae-4878-a539-0493a002fe51"),
                            Url = "https://i.ebayimg.com/images/g/fkUAAOSwG4pctJCS/s-l1600.jpg"
                        },
                        new
                        {
                            Id = new Guid("776926e0-d6b2-498c-9fe9-7d1b49426797"),
                            AssetsType = 0,
                            ProductId = new Guid("5a0aefdb-46ae-4878-a539-0493a002fe51"),
                            Url = "https://i.ebayimg.com/images/g/fkUAAOSwG4pctJCS/s-l1600.jpg"
                        });
                });

            modelBuilder.Entity("MarketProj.Models.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Clothes")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<double>("DiscountPrice")
                        .HasColumnType("float");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Clothes");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44a49261-e520-48e0-9b8f-32a3287ac366"),
                            Clothes = 0,
                            Color = "White",
                            Date = new DateTime(2020, 6, 15, 17, 2, 0, 22, DateTimeKind.Local).AddTicks(9469),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 1,
                            Model = "Nike",
                            Name = "Buisnes Shirt",
                            Price = 20.0,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("7d16bcaf-37ac-4e42-8619-38d9afd2e798"),
                            Clothes = 1,
                            Color = "Black",
                            Date = new DateTime(2020, 6, 15, 17, 2, 0, 26, DateTimeKind.Local).AddTicks(7342),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 1,
                            Model = "Levis",
                            Name = "Buisnes Short",
                            Price = 25.0,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("12173eb7-78c8-43ac-a171-6ff8ed5b6c23"),
                            Clothes = 2,
                            Color = "Black",
                            Date = new DateTime(2020, 6, 15, 17, 2, 0, 26, DateTimeKind.Local).AddTicks(7846),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 2,
                            Model = "Adidas",
                            Name = "Sport Nice",
                            Price = 25.0,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("5a0aefdb-46ae-4878-a539-0493a002fe51"),
                            Clothes = 3,
                            Color = "Blue",
                            Date = new DateTime(2020, 6, 15, 17, 2, 0, 26, DateTimeKind.Local).AddTicks(7865),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 2,
                            Model = "Hugo",
                            Name = "Hat",
                            Price = 12.5,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("f708dd0c-781a-420c-bd09-404e9210d0a8"),
                            Clothes = 3,
                            Color = "Blue",
                            Date = new DateTime(2020, 6, 15, 17, 2, 0, 26, DateTimeKind.Local).AddTicks(7901),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 2,
                            Model = "Diamond",
                            Name = "Earrings Golden",
                            Price = 200.5,
                            Size = 32.0
                        });
                });

            modelBuilder.Entity("MarketProj.Models.Models.UserProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf566828-49bf-4393-9e9d-d23f565f05d4"),
                            ProductId = new Guid("44a49261-e520-48e0-9b8f-32a3287ac366"),
                            UserId = new Guid("2e5e7149-2410-4997-a4b0-e634b36039a0")
                        },
                        new
                        {
                            Id = new Guid("2f3a757f-8e79-47cf-ad10-10180a4e66e2"),
                            ProductId = new Guid("7d16bcaf-37ac-4e42-8619-38d9afd2e798"),
                            UserId = new Guid("2e5e7149-2410-4997-a4b0-e634b36039a0")
                        },
                        new
                        {
                            Id = new Guid("24b0ca82-9591-43f9-a2cc-5f63af50db1a"),
                            ProductId = new Guid("7d16bcaf-37ac-4e42-8619-38d9afd2e798"),
                            UserId = new Guid("84a6eda2-2ba2-43ed-8006-b07de7403e3d")
                        });
                });

            modelBuilder.Entity("MarketProj.Models.Models.Assets", b =>
                {
                    b.HasOne("MarketProj.Models.Models.Product", "Product")
                        .WithMany("Assets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
