// <auto-generated />
using System;
using MarketProj.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketProj.DAL.Migrations
{
    [DbContext(typeof(MarketDB))]
    [Migration("20200614215419_dataSeed_Assets")]
    partial class dataSeed_Assets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarketProj.Models.Models.Assets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetsType")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9cc3989b-083b-45e6-95c0-01462eb35e39"),
                            AssetsType = 0,
                            ProductId = new Guid("3665ed66-c9be-4e7f-88c7-881fe37f5af2"),
                            Url = "https://i.ebayimg.com/images/g/RgUAAOSwatBb8s0m/s-l1600.jpg"
                        },
                        new
                        {
                            Id = new Guid("600ebb44-d93c-4d9e-b955-6b4ab0bd0bc3"),
                            AssetsType = 0,
                            ProductId = new Guid("3665ed66-c9be-4e7f-88c7-881fe37f5af2"),
                            Url = "https://i.ebayimg.com/images/g/op0AAOSwhnlb8s0f/s-l1600.jpg"
                        },
                        new
                        {
                            Id = new Guid("a05ee80d-1830-44db-b300-8fd1188ebbf0"),
                            AssetsType = 0,
                            ProductId = new Guid("b94f2e29-4699-4aa7-8da7-0b493acf11b0"),
                            Url = "https://www.llbeanbusiness.com/static/cms-img/classic-oxford-shirts-f19.jpg"
                        },
                        new
                        {
                            Id = new Guid("67a2668d-37be-4c18-ab70-92c9aaca23ff"),
                            AssetsType = 0,
                            ProductId = new Guid("b94f2e29-4699-4aa7-8da7-0b493acf11b0"),
                            Url = "https://images-na.ssl-images-amazon.com/images/I/61TWxMB8LFL._AC_UX679_.jpg"
                        },
                        new
                        {
                            Id = new Guid("f4c69ad7-fa7d-4f2e-88b1-db10990d02d2"),
                            AssetsType = 0,
                            ProductId = new Guid("7874d194-060f-4227-991b-ed4f7d6b9b98"),
                            Url = "https://i.ebayimg.com/images/g/fkUAAOSwG4pctJCS/s-l1600.jpg"
                        },
                        new
                        {
                            Id = new Guid("24eb8030-fe45-4de5-acb2-9ee48f696653"),
                            AssetsType = 0,
                            ProductId = new Guid("7874d194-060f-4227-991b-ed4f7d6b9b98"),
                            Url = "https://i.ebayimg.com/images/g/fkUAAOSwG4pctJCS/s-l1600.jpg"
                        });
                });

            modelBuilder.Entity("MarketProj.Models.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Clothes")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<double>("DiscountPrice")
                        .HasColumnType("float");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Clothes");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b94f2e29-4699-4aa7-8da7-0b493acf11b0"),
                            Clothes = 0,
                            Color = "White",
                            Date = new DateTime(2020, 6, 15, 1, 54, 19, 279, DateTimeKind.Local).AddTicks(9735),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 1,
                            Model = "Nike",
                            Name = "Buisnes Shirt",
                            Price = 20.0,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("3665ed66-c9be-4e7f-88c7-881fe37f5af2"),
                            Clothes = 1,
                            Color = "Black",
                            Date = new DateTime(2020, 6, 15, 1, 54, 19, 282, DateTimeKind.Local).AddTicks(330),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 1,
                            Model = "Levis",
                            Name = "Buisnes Short",
                            Price = 25.0,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("9ed5281e-ec55-41d0-9d4b-01899a11bff5"),
                            Clothes = 2,
                            Color = "Black",
                            Date = new DateTime(2020, 6, 15, 1, 54, 19, 282, DateTimeKind.Local).AddTicks(542),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 2,
                            Model = "Adidas",
                            Name = "Sport Nice",
                            Price = 25.0,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("7874d194-060f-4227-991b-ed4f7d6b9b98"),
                            Clothes = 3,
                            Color = "Blue",
                            Date = new DateTime(2020, 6, 15, 1, 54, 19, 282, DateTimeKind.Local).AddTicks(550),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 2,
                            Model = "Hugo",
                            Name = "Hat",
                            Price = 12.5,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("e8776cb0-c3a6-43f5-a024-01f11170feaf"),
                            Clothes = 3,
                            Color = "Blue",
                            Date = new DateTime(2020, 6, 15, 1, 54, 19, 282, DateTimeKind.Local).AddTicks(556),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 2,
                            Model = "Diamond",
                            Name = "Earrings Golden",
                            Price = 200.5,
                            Size = 32.0
                        });
                });

            modelBuilder.Entity("MarketProj.Models.Models.UserProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("MarketProj.Models.Models.Assets", b =>
                {
                    b.HasOne("MarketProj.Models.Models.Product", "Product")
                        .WithMany("Assets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
