// <auto-generated />
using System;
using MarketProj.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketProj.DAL.Migrations
{
    [DbContext(typeof(MarketDB))]
    [Migration("20200614212430_dataSeed")]
    partial class dataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarketProj.Models.Models.Assets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetsType")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MarketProj.Models.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Clothes")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<double>("DiscountPrice")
                        .HasColumnType("float");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Clothes");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04b28c9b-0944-4b34-a933-410e2f265f1e"),
                            Clothes = 0,
                            Color = "White",
                            Date = new DateTime(2020, 6, 15, 1, 24, 29, 926, DateTimeKind.Local).AddTicks(3288),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 1,
                            Model = "Nike",
                            Name = "Buisnes Shirt",
                            Price = 20.0,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("e04b5142-e8cf-436f-86b1-ff35243306cf"),
                            Clothes = 1,
                            Color = "Black",
                            Date = new DateTime(2020, 6, 15, 1, 24, 29, 928, DateTimeKind.Local).AddTicks(4939),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 1,
                            Model = "Levis",
                            Name = "Buisnes Short",
                            Price = 25.0,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("2e1e4375-43fc-4c82-9ebd-63f8e916af3b"),
                            Clothes = 2,
                            Color = "Black",
                            Date = new DateTime(2020, 6, 15, 1, 24, 29, 928, DateTimeKind.Local).AddTicks(5151),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 2,
                            Model = "Adidas",
                            Name = "Sport Nice",
                            Price = 25.0,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("f7acc7af-3c20-483d-a235-55a6938b7643"),
                            Clothes = 3,
                            Color = "Blue",
                            Date = new DateTime(2020, 6, 15, 1, 24, 29, 928, DateTimeKind.Local).AddTicks(5172),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 2,
                            Model = "Hugo",
                            Name = "Hat",
                            Price = 12.5,
                            Size = 32.0
                        },
                        new
                        {
                            Id = new Guid("75f79c22-4141-43d5-a619-3efdef1feae6"),
                            Clothes = 3,
                            Color = "Blue",
                            Date = new DateTime(2020, 6, 15, 1, 24, 29, 928, DateTimeKind.Local).AddTicks(5256),
                            DiscountPercent = 0.0,
                            DiscountPrice = 0.0,
                            Gender = 2,
                            Model = "Diamond",
                            Name = "Earrings Golden",
                            Price = 200.5,
                            Size = 32.0
                        });
                });

            modelBuilder.Entity("MarketProj.Models.Models.UserProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("MarketProj.Models.Models.Assets", b =>
                {
                    b.HasOne("MarketProj.Models.Models.Product", "Product")
                        .WithMany("Assets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
